default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: react_accounts_development

test:
  <<: *default
  database: react_accounts_test

production:
  <<: *default
  database: react_accounts_production
  username: react_accounts
  password: <%= ENV['RAILS4BASE_DATABASE_PASSWORD'] %>
